version: '3.3'
volumes:
  data:
services:
  postgres_Desafio_Compass:
    image: postgres:latest
    container_name: postgres_Desafio_Compass
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=desafio_compass
      - POSTGRES_USER=compass
      - POSTGRES_PASSWORD=compass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
